// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpilibj/generate_hids.py. DO NOT MODIFY

package org.team4159.commandsv3backport.driverstation;

import edu.wpi.first.hal.FRCNetComm.tResourceType;
import edu.wpi.first.hal.HAL;
import edu.wpi.first.util.sendable.Sendable;
import edu.wpi.first.util.sendable.SendableBuilder;
import java.util.EnumSet;
import java.util.Objects;
import org.team4159.commandsv3backport.driverstation.GenericHID.HIDType;
import org.team4159.commandsv3backport.driverstation.GenericHID.RumbleType;
import org.team4159.commandsv3backport.driverstation.GenericHID.SupportedOutput;
import org.team4159.commandsv3backport.event.BooleanEvent;
import org.team4159.commandsv3backport.event.EventLoop;

/**
 * Handle input from NiDsXbox controllers connected to the Driver Station.
 *
 * <p>This class handles NiDsXbox input that comes from the Driver Station. Each time a value is
 * requested the most recent value is returned. There is a single class instance for each controller
 * and the mapping of ports to hardware buttons depends on the code in the Driver Station.
 *
 * <p>Only first party controllers from Microsoft are guaranteed to have the correct mapping, and
 * only through the official NI DS. Sim is not guaranteed to have the same mapping, as well as any
 * 3rd party controllers.
 */
@Deprecated
public class NiDsXboxController implements HIDDevice, Sendable {

    /** Represents a digital button on a NiDsXboxController. */
    public enum Button {
        /** A button. */
        A(0, "AButton"),
        /** B button. */
        B(1, "BButton"),
        /** X button. */
        X(2, "XButton"),
        /** Y button. */
        Y(3, "YButton"),
        /** Left bumper button. */
        LEFT_BUMPER(4, "LeftBumperButton"),
        /** Right bumper button. */
        RIGHT_BUMPER(5, "RightBumperButton"),
        /** Back button. */
        BACK(6, "BackButton"),
        /** Start button. */
        START(7, "StartButton"),
        /** Left stick button. */
        LEFT_STICK(8, "LeftStickButton"),
        /** Right stick button. */
        RIGHT_STICK(9, "RightStickButton");

        /** Button value. */
        public final int value;

        private final String m_name;

        Button(int value, String name) {
            this.value = value;
            m_name = name;
        }

        /**
         * Get the human-friendly name of the button, matching the relevant methods.
         *
         * <p>Primarily used for automated unit tests.
         *
         * @return the human-friendly name of the button.
         */
        @Override
        public String toString() {
            return m_name;
        }
    }

    /** Represents an axis on an NiDsXboxController. */
    public enum Axis {
        /** Left X axis. */
        LEFT_X(0, "LeftX"),
        /** Right X axis. */
        RIGHT_X(4, "RightX"),
        /** Left Y axis. */
        LEFT_Y(1, "LeftY"),
        /** Right Y axis. */
        RIGHT_Y(5, "RightY"),
        /** Left trigger. */
        LEFT_TRIGGER(2, "LeftTriggerAxis"),
        /** Right trigger. */
        RIGHT_TRIGGER(3, "RightTriggerAxis");

        /** Axis value. */
        public final int value;

        private final String m_name;

        Axis(int value, String name) {
            this.value = value;
            m_name = name;
        }

        /**
         * Get the human-friendly name of the axis, matching the relevant methods.
         *
         * <p>Primarily used for automated unit tests.
         *
         * @return the human-friendly name of the axis.
         */
        @Override
        public String toString() {
            return m_name;
        }
    }

    private final GenericHID m_hid;

    /**
     * Get the underlying GenericHID object.
     *
     * @return the wrapped GenericHID object
     */
    @Override
    public GenericHID getHID() {
        return m_hid;
    }

    /**
     * Construct an instance of a controller.
     *
     * @param port The port index on the Driver Station that the controller is plugged into (0-5).
     */
    public NiDsXboxController(final int port) {
        this(new GenericHID(port));
    }

    /**
     * Construct an instance of a controller with a GenericHID object.
     *
     * @param hid The GenericHID object to use for this controller.
     */
    public NiDsXboxController(final GenericHID hid) {
        m_hid = Objects.requireNonNull(hid, "Provided HID object cannot be null");
        HAL.report(tResourceType.kResourceType_Controller, hid.getPort(), 0, "NiDsXboxController");
    }

    /**
     * Get the X axis value of left side of the controller. Right is positive.
     *
     * @return The axis value.
     */
    public double getLeftX() {
        return m_hid.getRawAxis(Axis.LEFT_X.value);
    }

    /**
     * Get the X axis value of right side of the controller. Right is positive.
     *
     * @return The axis value.
     */
    public double getRightX() {
        return m_hid.getRawAxis(Axis.RIGHT_X.value);
    }

    /**
     * Get the Y axis value of left side of the controller. Back is positive.
     *
     * @return The axis value.
     */
    public double getLeftY() {
        return m_hid.getRawAxis(Axis.LEFT_Y.value);
    }

    /**
     * Get the Y axis value of right side of the controller. Back is positive.
     *
     * @return The axis value.
     */
    public double getRightY() {
        return m_hid.getRawAxis(Axis.RIGHT_Y.value);
    }

    /**
     * Get the left trigger axis value of the controller. Note that this axis is bound to the
     * range of [0, 1] as opposed to the usual [-1, 1].
     *
     * @return The axis value.
     */
    public double getLeftTriggerAxis() {
        return m_hid.getRawAxis(Axis.LEFT_TRIGGER.value);
    }

    /**
     * Constructs an event instance around the axis value of the left trigger. The returned trigger
     * will be true when the axis value is greater than {@code threshold}.
     *
     * @param threshold the minimum axis value for the returned {@link BooleanEvent} to be true. This
     *     value should be in the range [0, 1] where 0 is the unpressed state of the axis.
     * @param loop the event loop instance to attach the event to.
     * @return an event instance that is true when the left trigger's axis exceeds the provided
     *     threshold, attached to the given event loop
     */
    public BooleanEvent leftTrigger(double threshold, EventLoop loop) {
        return m_hid.axisGreaterThan(Axis.LEFT_TRIGGER.value, threshold, loop);
    }

    /**
     * Constructs an event instance around the axis value of the left trigger. The returned trigger
     * will be true when the axis value is greater than 0.5.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance that is true when the left trigger's axis exceeds the provided
     *     threshold, attached to the given event loop
     */
    public BooleanEvent leftTrigger(EventLoop loop) {
        return leftTrigger(0.5, loop);
    }

    /**
     * Get the right trigger axis value of the controller. Note that this axis is bound to the
     * range of [0, 1] as opposed to the usual [-1, 1].
     *
     * @return The axis value.
     */
    public double getRightTriggerAxis() {
        return m_hid.getRawAxis(Axis.RIGHT_TRIGGER.value);
    }

    /**
     * Constructs an event instance around the axis value of the right trigger. The returned trigger
     * will be true when the axis value is greater than {@code threshold}.
     *
     * @param threshold the minimum axis value for the returned {@link BooleanEvent} to be true. This
     *     value should be in the range [0, 1] where 0 is the unpressed state of the axis.
     * @param loop the event loop instance to attach the event to.
     * @return an event instance that is true when the right trigger's axis exceeds the provided
     *     threshold, attached to the given event loop
     */
    public BooleanEvent rightTrigger(double threshold, EventLoop loop) {
        return m_hid.axisGreaterThan(Axis.RIGHT_TRIGGER.value, threshold, loop);
    }

    /**
     * Constructs an event instance around the axis value of the right trigger. The returned trigger
     * will be true when the axis value is greater than 0.5.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance that is true when the right trigger's axis exceeds the provided
     *     threshold, attached to the given event loop
     */
    public BooleanEvent rightTrigger(EventLoop loop) {
        return rightTrigger(0.5, loop);
    }

    /**
     * Read the value of the A button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getAButton() {
        return m_hid.getRawButton(Button.A.value);
    }

    /**
     * Whether the A button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getAButtonPressed() {
        return m_hid.getRawButtonPressed(Button.A.value);
    }

    /**
     * Whether the A button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getAButtonReleased() {
        return m_hid.getRawButtonReleased(Button.A.value);
    }

    /**
     * Constructs an event instance around the A button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the A button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent a(EventLoop loop) {
        return m_hid.button(Button.A.value, loop);
    }

    /**
     * Read the value of the B button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getBButton() {
        return m_hid.getRawButton(Button.B.value);
    }

    /**
     * Whether the B button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getBButtonPressed() {
        return m_hid.getRawButtonPressed(Button.B.value);
    }

    /**
     * Whether the B button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getBButtonReleased() {
        return m_hid.getRawButtonReleased(Button.B.value);
    }

    /**
     * Constructs an event instance around the B button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the B button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent b(EventLoop loop) {
        return m_hid.button(Button.B.value, loop);
    }

    /**
     * Read the value of the X button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getXButton() {
        return m_hid.getRawButton(Button.X.value);
    }

    /**
     * Whether the X button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getXButtonPressed() {
        return m_hid.getRawButtonPressed(Button.X.value);
    }

    /**
     * Whether the X button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getXButtonReleased() {
        return m_hid.getRawButtonReleased(Button.X.value);
    }

    /**
     * Constructs an event instance around the X button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the X button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent x(EventLoop loop) {
        return m_hid.button(Button.X.value, loop);
    }

    /**
     * Read the value of the Y button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getYButton() {
        return m_hid.getRawButton(Button.Y.value);
    }

    /**
     * Whether the Y button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getYButtonPressed() {
        return m_hid.getRawButtonPressed(Button.Y.value);
    }

    /**
     * Whether the Y button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getYButtonReleased() {
        return m_hid.getRawButtonReleased(Button.Y.value);
    }

    /**
     * Constructs an event instance around the Y button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the Y button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent y(EventLoop loop) {
        return m_hid.button(Button.Y.value, loop);
    }

    /**
     * Read the value of the left bumper button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getLeftBumperButton() {
        return m_hid.getRawButton(Button.LEFT_BUMPER.value);
    }

    /**
     * Whether the left bumper button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getLeftBumperButtonPressed() {
        return m_hid.getRawButtonPressed(Button.LEFT_BUMPER.value);
    }

    /**
     * Whether the left bumper button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getLeftBumperButtonReleased() {
        return m_hid.getRawButtonReleased(Button.LEFT_BUMPER.value);
    }

    /**
     * Constructs an event instance around the left bumper button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the left bumper button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent leftBumper(EventLoop loop) {
        return m_hid.button(Button.LEFT_BUMPER.value, loop);
    }

    /**
     * Read the value of the right bumper button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getRightBumperButton() {
        return m_hid.getRawButton(Button.RIGHT_BUMPER.value);
    }

    /**
     * Whether the right bumper button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getRightBumperButtonPressed() {
        return m_hid.getRawButtonPressed(Button.RIGHT_BUMPER.value);
    }

    /**
     * Whether the right bumper button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getRightBumperButtonReleased() {
        return m_hid.getRawButtonReleased(Button.RIGHT_BUMPER.value);
    }

    /**
     * Constructs an event instance around the right bumper button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the right bumper button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent rightBumper(EventLoop loop) {
        return m_hid.button(Button.RIGHT_BUMPER.value, loop);
    }

    /**
     * Read the value of the back button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getBackButton() {
        return m_hid.getRawButton(Button.BACK.value);
    }

    /**
     * Whether the back button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getBackButtonPressed() {
        return m_hid.getRawButtonPressed(Button.BACK.value);
    }

    /**
     * Whether the back button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getBackButtonReleased() {
        return m_hid.getRawButtonReleased(Button.BACK.value);
    }

    /**
     * Constructs an event instance around the back button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the back button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent back(EventLoop loop) {
        return m_hid.button(Button.BACK.value, loop);
    }

    /**
     * Read the value of the start button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getStartButton() {
        return m_hid.getRawButton(Button.START.value);
    }

    /**
     * Whether the start button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getStartButtonPressed() {
        return m_hid.getRawButtonPressed(Button.START.value);
    }

    /**
     * Whether the start button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getStartButtonReleased() {
        return m_hid.getRawButtonReleased(Button.START.value);
    }

    /**
     * Constructs an event instance around the start button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the start button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent start(EventLoop loop) {
        return m_hid.button(Button.START.value, loop);
    }

    /**
     * Read the value of the left stick button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getLeftStickButton() {
        return m_hid.getRawButton(Button.LEFT_STICK.value);
    }

    /**
     * Whether the left stick button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getLeftStickButtonPressed() {
        return m_hid.getRawButtonPressed(Button.LEFT_STICK.value);
    }

    /**
     * Whether the left stick button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getLeftStickButtonReleased() {
        return m_hid.getRawButtonReleased(Button.LEFT_STICK.value);
    }

    /**
     * Constructs an event instance around the left stick button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the left stick button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent leftStick(EventLoop loop) {
        return m_hid.button(Button.LEFT_STICK.value, loop);
    }

    /**
     * Read the value of the right stick button on the controller.
     *
     * @return The state of the button.
     */
    public boolean getRightStickButton() {
        return m_hid.getRawButton(Button.RIGHT_STICK.value);
    }

    /**
     * Whether the right stick button was pressed since the last check.
     *
     * @return Whether the button was pressed since the last check.
     */
    public boolean getRightStickButtonPressed() {
        return m_hid.getRawButtonPressed(Button.RIGHT_STICK.value);
    }

    /**
     * Whether the right stick button was released since the last check.
     *
     * @return Whether the button was released since the last check.
     */
    public boolean getRightStickButtonReleased() {
        return m_hid.getRawButtonReleased(Button.RIGHT_STICK.value);
    }

    /**
     * Constructs an event instance around the right stick button's digital signal.
     *
     * @param loop the event loop instance to attach the event to.
     * @return an event instance representing the right stick button's digital signal
     *     attached to the given loop.
     */
    public BooleanEvent rightStick(EventLoop loop) {
        return m_hid.button(Button.RIGHT_STICK.value, loop);
    }

    /**
     * Get if the controller is connected.
     *
     * @return true if the controller is connected
     */
    public boolean isConnected() {
        return m_hid.isConnected();
    }

    /**
     * Get the type of the controller.
     *
     * @return the type of the controller.
     */
    public HIDType getGamepadType() {
        return m_hid.getGamepadType();
    }

    /**
     * Get the supported outputs of the controller.
     *
     * @return the supported outputs of the controller.
     */
    @Deprecated
    public EnumSet<SupportedOutput> getSupportedOutputs() {
        return m_hid.getSupportedOutputs();
    }

    /**
     * Get the name of the controller.
     *
     * @return the name of the controller.
     */
    public String getName() {
        return m_hid.getName();
    }

    /**
     * Get the port number of the controller.
     *
     * @return The port number of the controller.
     */
    public int getPort() {
        return m_hid.getPort();
    }

    /**
     * Set the rumble output for the HID.
     *
     * <p>The DS currently supports 4 rumble values: left rumble, right rumble, left trigger rumble,
     * and right trigger rumble.
     *
     * @param type Which rumble value to set
     * @param value The normalized value (0 to 1) to set the rumble to
     */
    public void setRumble(RumbleType type, double value) {
        m_hid.setRumble(type, value);
    }

    @Override
    public void initSendable(SendableBuilder builder) {
        builder.setSmartDashboardType("HID");
        builder.publishConstString("ControllerType", "NiDsXbox");
        builder.addDoubleProperty("LeftTrigger Axis", this::getLeftTriggerAxis, null);
        builder.addDoubleProperty("RightTrigger Axis", this::getRightTriggerAxis, null);
        builder.addDoubleProperty("LeftX", this::getLeftX, null);
        builder.addDoubleProperty("RightX", this::getRightX, null);
        builder.addDoubleProperty("LeftY", this::getLeftY, null);
        builder.addDoubleProperty("RightY", this::getRightY, null);
        builder.addBooleanProperty("A", this::getAButton, null);
        builder.addBooleanProperty("B", this::getBButton, null);
        builder.addBooleanProperty("X", this::getXButton, null);
        builder.addBooleanProperty("Y", this::getYButton, null);
        builder.addBooleanProperty("LeftBumper", this::getLeftBumperButton, null);
        builder.addBooleanProperty("RightBumper", this::getRightBumperButton, null);
        builder.addBooleanProperty("Back", this::getBackButton, null);
        builder.addBooleanProperty("Start", this::getStartButton, null);
        builder.addBooleanProperty("LeftStick", this::getLeftStickButton, null);
        builder.addBooleanProperty("RightStick", this::getRightStickButton, null);
    }
}
